QnA APIs for Lecture Support Platform
skkuding/skku-coding-platform pull request #279
Opened 2022-01-12 07:32 UTC by aintbe

QnA 페이지 구현을 위한 qna app을 추가했습니다. 수정사항 피드백 부탁드립니다!  
- QuestionStudentAPI: `post`/`put`/`get`/`delete`
- QuestionProfessorAPI: `get`
- AnswerAPI: `post`/`put`/`get`/`delete` + close with this comment 기능

2022-02-03 18:05 UTC, minseo999 requested changes

2022-02-03 18:05 UTC, minseo999 commented on backend/qna/views/student.py
> +        except Answer.DoesNotExist:
filter query에서는 doesnotexist 에러가 발생하지 않습니다!

2022-02-10 15:31 UTC, aintbe commented on backend/qna/views/student.py
> +        if data.pop("closure", False):
답글 입력 시 프론트엔드에서 `close QnA with this comment` 옵션을 줄 수 있는데, 해당 옵션이 체크되었는지를 담고 있는 필드입니다!

2022-02-10 15:31 UTC, aintbe commented on backend/qna/views/student.py
> +        if answer.created_by != request.user and not request.user.is_super_admin():
설계서에는 super admin에게는 수정 권한이 부여되는 것으로 짜여 있어서 위와 같이 구현했습니다! 변경하는 게 좋을까요?

c.f. 노션 > 기능 명세 > 강의 지원 플랫폼 Student UI 설계서v1.2

2022-02-14 16:12 UTC, minseo999 commented on backend/qna/views/student.py
> +        if answer.created_by != request.user and not request.user.is_super_admin():
네 저는 수정 권한 주지 않아도 될 것 같아요!

2022-02-14 16:23 UTC, minseo999 requested changes

2022-02-14 16:23 UTC, minseo999 commented on backend/account/models.py
> +        return self.is_authenticated and question.created_by == self
is_question_admin 에도 super admin 포함시키면 좋을 것 같아요!

2022-02-14 16:23 UTC, minseo999 commented on backend/qna/views/student.py
> +            if not request.user.is_question_admin(question) and not request.user.is_super_admin():
is_question_admin 에 super admin도 포함하면 여기도 수정해주세요!

2022-02-20 14:53 UTC, jimin9038 commented
여기 제가 커밋 정리 해두 될까요?? QnA 프론트 구현하는데 테스트가 너무 어렵다고 하네요 😢

2022-02-21 03:10 UTC, aintbe commented
@jimin9038 커밋 정리하셔도 괜찮아요! 그런데 force push 때문에 마지막 커밋 하나([c5d7db9](https://github.com/skkuding/skku-coding-platform/commit/c5d7db964366e2e186a3db051054ae05f872a0d8))가 날아가서 제가 다시 커밋해야 할 것 같은데, 정리 작업 끝나신 건가요?

2022-02-21 03:13 UTC, jimin9038 commented
@aintbe 아 그렇군요 😢 정리는 다 했고, c5d7db9 반영해주면 될 것 같습니다!

2022-02-21 03:18 UTC, jimin9038 commented
@aintbe 잠시만요! 커밋 몇개가 날라간 것 같아서 확인좀 해볼게요

2022-02-21 04:33 UTC, jimin9038 commented
@aintbe 정리 다 된것 같고 https://github.com/skkuding/skku-coding-platform/commit/c5d7db964366e2e186a3db051054ae05f872a0d8 도 cherrypick해서 올려두었습니다. 틀린 것 없는지 한번 확인해주세요!

2022-02-21 07:34 UTC, aintbe commented
@jimin9038 전체적으로 확인했어요! 문제 없는 것 같습니다!😄

2022-02-22 13:33 UTC, jimin9038 requested changes

2022-02-22 13:33 UTC, jimin9038 commented on backend/qna/urls/professor.py
> +    path("course/question", QuestionAPI.as_view(), name="question_professor_api"),
url 끝에 슬래시 다 붙여주세요!

2022-02-22 13:33 UTC, jimin9038 commented on backend/qna/urls/student.py
> +    path("course/question", QuestionAPI.as_view(), name="question_api"),
url 끝에 슬래시 다 붙여주세요!

2022-03-01 14:36 UTC, jimin9038 commented
1. 댓글에서 편집을 하니까 그 위에 내용도 같이 바뀐다.
2. 배지 위치가 Edit / Delete가 없을 때 왼쪽에 고정되서 안 예쁘다.
3. Resolved에서 댓글을 달면 question does not exist가 뜬다 -> 해결

2022-03-02 23:33 UTC, aintbe commented
@jimin9038 문제 없는 것 같습니다! 해당 부분 수정했어요!

2022-03-03 02:41 UTC, jimin9038 commented
> @jimin9038 문제 없는 것 같습니다! 해당 부분 수정했어요!

넵!! 👍

2022-03-16 07:00 UTC, jimin9038 approved these changes
Edit question 안되는 부분만 약간 수정했어요. 이제 잘 되는 것 같습니다 👍

2022-04-12 06:15 UTC, merged