Add profileSubmissionListAPI in Profile Page
skkuding/skku-coding-platform pull request #308
Opened 2022-02-24 12:38 UTC by st42597

API작성하면서 필요한 데이터 model에 추가했습니다.
front와 연결하는 것까지 끝냈고 정상적으로 작동합니다.
submission model에 문제 번호인 _id가 없어서 keyword검색할 때 문제 title로만 검색이 되는데 문제 번호로도 검색이 되는게 좋을까요?

2022-02-26 03:36 UTC, jimin9038 requested changes

2022-02-26 03:36 UTC, jimin9038 commented on backend/submission/views.py
> +        print(submissions)
print 지워주세요!

2022-02-26 03:36 UTC, jimin9038 commented on frontend/src/pages/oj/components/user/ProfileSubmission.vue
> +    async getProfileSubmissionList () {
getProfileSubmissionList api가 처음에 50개를 불러오고, 그 뒤로는 안 불러오는 것으로 보입니다. pagination을 통해 페이지를 바꿀 때마다 20개씩 불러오도록 바꾸는게 어떨까요? (admin/announcement.vue에서 pagination쪽 참고)

2022-03-01 05:56 UTC, st42597 commented on backend/submission/views.py
> +                                               code_length=len(str(data["code"])),
https://d2.naver.com/helloworld/19187
한글 코드 크기 문제에 대해서 알아보니 인코딩 방식에 따라서 크기가 다르네요.
<img width="327" alt="스크린샷 2022-03-01 오후 2 51 10" src="https://user-images.githubusercontent.com/67233988/156112726-ccb58c09-6fae-494e-a8e7-1eb1a7453acb.png">
utf-8기준으로 인코딩하면 한글 한 음절(초성 + 중성, 초성 + 중성 + 종성)관계없이 3bytes라서 4 * 1 + 3 * 3으로 13bytes가 나옵니다.
DB 인코딩 방식에 맞추는게 좋아보이는데 혹시 어떤거 사용하는지 아시나요??

2022-03-01 05:59 UTC, dotoleeoak commented on backend/submission/views.py
> +                                               code_length=len(str(data["code"])),
따로 설정이 없으면 UTF-8입니다. 아래 코드처럼 하면 될 것 같아요.

```python
len(data["code"].encode('utf-8'))
```

2022-03-01 06:00 UTC, st42597 commented on backend/submission/views.py
> +                                               code_length=len(str(data["code"])),
넵 감사합니다

2022-03-01 12:53 UTC, jimin9038 approved these changes
👍

2022-03-01 12:54 UTC, merged